### PR TITLE
Changed the css-selectors lib to reduce # of dependencies...

### PR DESCRIPTION
**Pull request by gbranchaud**
Replaced the com.3levers.cssselectors lib by the se.fishtank.css-selectors lib. 

css-selectors has no dependencies and was nearly a drop-in replacement.

Sadly, a small breaking change occurred: a selector of  ``#my-id`` will not match anything in the document ``<div id='my-id'></div>``. This is consistent with how the W3C defines the [``querySelectorAll()``](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll) method (only descendants of the root are considered.)

I updated the tests so they use a more complete document: instead of passing a single element, they now pass something like ``<html><body><div></div></body></html>``.

Would you be interested in working with me to get this change approved and published?
Maybe a little perfection game?

Note: the only motivation behind this change is reducing the number of jars pulled by this lib.

### CODE REVIEW

**Comment by testinfected** [comment]
Hi Gab,

Before I can do a perfection game, will you tell me more about the limitation you described above. Specifically, how does the lib behave when selecting `#my-id` from `<div><div id='my-id'></div></div>`? Am I correct in expecting it to select `#my-id`?

**Comment by gbranchaud** [comment]
You are correct.
Selecting ``#my-id`` from ``<div><div id='my-id'></div>`` will select the ``#my-id`` div.

**Comment by testinfected** [comment]
Great. I like that this library has no dependency and follows as closely as possible the w3c selector api.

To make it perfect I would to the following:
- throw an `IllegalArgumentException` when the selector expression is invalid instead of silently ignoring the error
- use a construct similar to the Selector we had before, e.g.: 

```java
public class Selector {
    private final Node root;
    
    private Selector(Node root) {
        this.root = root;
    }
    
    public static Selector from(Node root) {
        return new Selector(root);
    }

    public Set<Node> selectAll(String selector) {
        try {
            return new DOMNodeSelector(root).querySelectorAll(selector);
        } catch (NodeSelectorException e) {
            throw new IllegalArgumentException("Selector expression is invalid: " + selector, e);
        }
    }
}
```

- eliminate the duplication introduced in the tests by wrapping test fragments using a helper method private to the test class, something like ```assertMatches(hasNoSelector("#unknown"), html("<div id='content'>content</div>"));```

If you can make the changes, I will gladly merge the pull requests.

**Comment by gbranchaud** [comment]
Great feedback! I am really happy about the duplication reduction in the tests.

I went ahead and implemented the ``Selector`` class and the simple ``html`` helper.

**Pull request merged**
